export const renderClaude = (bundle) =>
  `# CLAUDE.md\n\nThis file is auto-generated by \`pnpm rules:compile\`.\nDo not edit manually. Edit files in \`/rules\` and recompile.\n\n## Project Rules\n\n${bundle}\n`
